### ISSUE TITLE
player crash on kill (xpCalculator) 

### ISSUE THREAD

**Issue by charliegustard** [Aurora-MC/AfterLife#4]
27.01 20:00:41 [Server] Server thread/CRITICAL ErrorException: "Undefined index: kill-streak" (EXCEPTION) in "AfterLife-master/src/atom/afterlife/modules/xpCalculator" at line 31
27.01 20:00:41 [Server] Server thread/INFO RekingPixel[/1.124.105.191:30506] logged out due to Internal server error

**Comment by Atomization** [comment]
Fixed once again, hope thats the last of errors ;), let me know if you experience any more errors
