### ISSUE TITLE
player crash on kill (Death Counter)

### ISSUE THREAD

**Issue by charliegustard** [Aurora-MC/AfterLife#5]
27.01 21:09:59 [Server] Server thread/CRITICAL ErrorException: "Undefined index: kill-streak" (EXCEPTION) in "AfterLife-master/src/atom/afterlife/modules/DeathCounter" at line 31
27.01 21:09:59 [Server] Server thread/INFO RekingPixel[/1.124.105.191:36538] logged out due to Internal server error

**Comment by Atomization** [comment]
Fixed once again! (i double checked this time, should be fixed)
